server:
  servlet:
    context-path: /api
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/manga?useUnicode=true&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect